[package]
name = "Qootrans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
dlopen = "*"
dlopen_derive = "*"
encoding = "*"
rayon = "*"
num_cpus = "*"